#!/bin/sh

cp -R /home/builder/pokemon_gen3_to_genx/. .

make -f Makefile.arm9 clean
make -f Makefile.arm9 2>&1 >/dev/null | grep ^$(pwd);

mkdir -p /home/builder/pokemon_gen3_to_genx/out
cp FPS_Editing_Testing.nds /home/builder/pokemon_gen3_to_genx/out/fps_editing_testing.nds


