#!/bin/sh

cp -R /home/builder/pokemon_gen3_to_genx/. .

make clean
make 2>&1 >/dev/null | grep ^$(pwd);

mkdir -p /home/builder/pokemon_gen3_to_genx/out
cp building_mb.gba /home/builder/pokemon_gen3_to_genx/out/pokemon_gen3_to_genx_mb.gba


