#ifndef MULTIBOOT_HANDLER__
#define MULTIBOOT_HANDLER__

#define MULTIBOOT_MAX_SIZE 0x3FF40

enum MULTIBOOT_RESULTS {MB_SUCCESS, MB_NO_INIT_SYNC, MB_WRONG_ANSWER, MB_HEADER_ISSUE, MB_PALETTE_FAILURE, MB_SWI_FAILURE};

enum MULTIBOOT_RESULTS multiboot_normal(u16*, u16*, int);

#endif
