#ifndef TIMING_BASIC__
#define TIMING_BASIC__

#define FPS 60
#define CLOCK_SPEED 16777216
#define NS_PER_SECOND 1000000000
#define NS_PER_CYCLE ((NS_PER_SECOND/CLOCK_SPEED)+((NS_PER_SECOND%CLOCK_SPEED) == 0 ? 0 : 1))
#define CYCLES_PER_SCANLINE 1232
#define NS_PER_SCANLINE (CYCLES_PER_SCANLINE*NS_PER_CYCLE)

#define GBA_CLOCK_SPEED 16777216

#endif
